FROM python:3.12-alpine

WORKDIR /work
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY convert.py /app/convert.py

ENTRYPOINT ["python", "/app/convert.py"]
